# name: Java CI with Maven

# on: push

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up JDK 8
#       uses: actions/setup-java@v3
#       with:
#         java-version: '8'
#         distribution: 'temurin'
#         cache: maven
#     - name: Build with Maven
#       run: mvn package
#     - name: Archive artifacts
#       uses: actions/upload-artifact@v2
#       with:
#         name: maven-artifacts
#         path: target/*.jar 
# #     - name: tomcat deploy
# #       run: curl -v -u  ${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }} -T /home/ec2-user/actions-runner/_work/spring3-mvc-maven-xml-hello-world/spring3-mvc-maven-xml-hello-world/target/spring3-mvc-maven-xml-hello-world-1.3.war 'http://65.2.37.3:8080/manager/text/deploy?path=/github_action_spring&update=true'
# # #
# # # 
name: Java CI with Maven
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      id: maven_build
      run: mvn package
    - name: Check for Maven artifacts
      run: |
        if [ ! -f target/*.jar ]; then
          echo "No artifacts found. Exiting..."
          exit 1
        fi
    - name: Archive artifacts
      if: success() && steps.maven_build.outputs.return-code == 0
      uses: actions/upload-artifact@v2
      with:
        name: maven-artifacts
        path: target/*.jar  
